### Create a Debit Bank Card
POST {{host}}/api/card
Content-Type: application/json

{
    "user": {
        "name": "Marsha",
        "surname": "Preyscott",
        "birthDate": "1989-11-09"
    },
    "type": "DEBIT"
}

> {% client.global.set("bankCard", response.body); %}

### Get a user by bank card number
GET {{host}}/api/card/{{bankCard}}

### Create a Credit Bank Card
POST {{host}}/api/card
Content-Type: application/json

{
	"user": {
		"name": "Albert",
		"surname": "Wells",
		"birthDate": "1954-07-28"
	},
	"type": "CREDIT"
}

> {% client.global.set("bankCard", response.body); %}

### Get a user by bank card number
GET {{host}}/api/card/{{bankCard}}

### Trying to find a user by unexistant bank card number
GET {{host}}/api/card/{{$random.uuid}}

### Get all bank cards
GET {{host}}/api/card
